// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloworld.proto

/*
Package helloworld is a generated protocol buffer package.

It is generated from these files:
	helloworld.proto

It has these top-level messages:
	HelloRequest
	HelloReply
	None
	UsersResponse
	User
*/
package helloworld

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Age  string `protobuf:"bytes,2,opt,name=age" json:"age,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HelloRequest) GetAge() string {
	if m != nil {
		return m.Age
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *HelloReply) Reset()                    { *m = HelloReply{} }
func (m *HelloReply) String() string            { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()               {}
func (*HelloReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type None struct {
}

func (m *None) Reset()                    { *m = None{} }
func (m *None) String() string            { return proto.CompactTextString(m) }
func (*None) ProtoMessage()               {}
func (*None) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type UsersResponse struct {
	Users []*User `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
}

func (m *UsersResponse) Reset()                    { *m = UsersResponse{} }
func (m *UsersResponse) String() string            { return proto.CompactTextString(m) }
func (*UsersResponse) ProtoMessage()               {}
func (*UsersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type User struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Age       string `protobuf:"bytes,2,opt,name=age" json:"age,omitempty"`
	Firstname string `protobuf:"bytes,3,opt,name=firstname" json:"firstname,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAge() string {
	if m != nil {
		return m.Age
	}
	return ""
}

func (m *User) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "helloworld.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "helloworld.HelloReply")
	proto.RegisterType((*None)(nil), "helloworld.None")
	proto.RegisterType((*UsersResponse)(nil), "helloworld.UsersResponse")
	proto.RegisterType((*User)(nil), "helloworld.User")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Greeter service

type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := grpc.Invoke(ctx, "/helloworld.Greeter/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Greeter service

type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld.proto",
}

// Client API for Database service

type DatabaseClient interface {
	GetUsers(ctx context.Context, in *None, opts ...grpc.CallOption) (*UsersResponse, error)
}

type databaseClient struct {
	cc *grpc.ClientConn
}

func NewDatabaseClient(cc *grpc.ClientConn) DatabaseClient {
	return &databaseClient{cc}
}

func (c *databaseClient) GetUsers(ctx context.Context, in *None, opts ...grpc.CallOption) (*UsersResponse, error) {
	out := new(UsersResponse)
	err := grpc.Invoke(ctx, "/helloworld.Database/GetUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Database service

type DatabaseServer interface {
	GetUsers(context.Context, *None) (*UsersResponse, error)
}

func RegisterDatabaseServer(s *grpc.Server, srv DatabaseServer) {
	s.RegisterService(&_Database_serviceDesc, srv)
}

func _Database_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(None)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Database/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServer).GetUsers(ctx, req.(*None))
	}
	return interceptor(ctx, in, info, handler)
}

var _Database_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Database",
	HandlerType: (*DatabaseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUsers",
			Handler:    _Database_GetUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld.proto",
}

func init() { proto.RegisterFile("helloworld.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x6d, 0x6c, 0x6c, 0xd3, 0x51, 0x31, 0xcc, 0x41, 0xd6, 0xea, 0xa1, 0xec, 0xa1, 0xf4, 0x14,
	0x24, 0x0a, 0xe2, 0xc5, 0x43, 0x51, 0xaa, 0x1e, 0xa4, 0x44, 0xc4, 0xf3, 0x56, 0xc7, 0x5a, 0xd8,
	0x64, 0xd7, 0xdd, 0x2d, 0x9a, 0xbf, 0x97, 0xdd, 0xaa, 0x8d, 0xe2, 0xc1, 0xdb, 0x7b, 0x6f, 0xde,
	0x30, 0xf3, 0x66, 0x20, 0x7d, 0x21, 0x29, 0xd5, 0x9b, 0x32, 0xf2, 0x29, 0xd3, 0x46, 0x39, 0x85,
	0xb0, 0x56, 0xf8, 0x09, 0x6c, 0x5f, 0x79, 0x56, 0xd0, 0xeb, 0x92, 0xac, 0x43, 0x84, 0xb8, 0x12,
	0x25, 0xb1, 0x68, 0x10, 0x8d, 0x7a, 0x45, 0xc0, 0x98, 0x42, 0x5b, 0xcc, 0x89, 0x6d, 0x04, 0xc9,
	0x43, 0x3e, 0x04, 0xf8, 0xec, 0xd2, 0xb2, 0x46, 0x06, 0xdd, 0x92, 0xac, 0xf5, 0x9e, 0x55, 0xdb,
	0x17, 0xe5, 0x1d, 0x88, 0x6f, 0x55, 0x45, 0xfc, 0x14, 0x76, 0xee, 0x2d, 0x19, 0x5b, 0x90, 0xd5,
	0xaa, 0xb2, 0x84, 0x43, 0xd8, 0x5c, 0x7a, 0x81, 0x45, 0x83, 0xf6, 0x68, 0x2b, 0x4f, 0xb3, 0xc6,
	0x92, 0xde, 0x59, 0xac, 0xca, 0xfc, 0x06, 0x62, 0x4f, 0xff, 0xb7, 0x16, 0x1e, 0x42, 0xef, 0x79,
	0x61, 0xac, 0x0b, 0xd6, 0x76, 0xd0, 0xd7, 0x42, 0x7e, 0x0d, 0xdd, 0x89, 0x21, 0x72, 0x64, 0xf0,
	0x1c, 0x92, 0x3b, 0x51, 0x87, 0x08, 0xc8, 0x9a, 0xb3, 0x9b, 0xb7, 0xe8, 0xef, 0xfd, 0x51, 0xd1,
	0xb2, 0xe6, 0xad, 0xfc, 0x12, 0x92, 0x0b, 0xe1, 0xc4, 0x4c, 0x58, 0xc2, 0x33, 0x48, 0x26, 0xe4,
	0x42, 0x3c, 0xfc, 0x91, 0xc3, 0x27, 0xef, 0xef, 0xff, 0x4e, 0xf6, 0x7d, 0x03, 0xde, 0x1a, 0x1f,
	0xc1, 0xc1, 0x42, 0x65, 0x73, 0xa3, 0x1f, 0x33, 0x7a, 0x17, 0xa5, 0x96, 0x64, 0x1b, 0xf6, 0xf1,
	0x6e, 0x98, 0xf9, 0xe0, 0xf1, 0xd4, 0x3f, 0x6e, 0x1a, 0xcd, 0x3a, 0xe1, 0x83, 0xc7, 0x1f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x97, 0x03, 0x2e, 0x44, 0xd5, 0x01, 0x00, 0x00,
}
